### ISSUE TITLE
API Integration with TolaData

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/aam-services#11]
**_Summary issue on all API Integration related topics_**

- [x] Aam-Digital/query-backend#5
- [x] Aam-Digital/query-backend#6
- [x] Aam-Digital/query-backend#7
- [x] Aam-Digital/query-backend#8
  - check schema generation from sqs report statement 
- [x] Aam-Digital/query-backend#15
- [x] Aam-Digital/query-backend#26
- [x] Aam-Digital/query-backend#20
- [x] Aam-Digital/query-backend#16
- [x] Aam-Digital/query-backend#9
- [x] Aam-Digital/query-backend#34
- [x] Aam-Digital/aam-services#8
- [ ] https://github.com/Aam-Digital/ndb-core/issues/2239
- [x] Aam-Digital/query-backend#33

Framework Migration
- [ ] migrate e2e tests
- [x] complete feature set
  - [x] trigger webhooks
- [x] deployment
- [x] logging/sentry

Later:
- [x] Logging
- [ ] simplify architecture and let report-changes module only create calculations, notifications module check for updates?
- [ ] improve change detection to avoid unnecessary calculations
- [ ] Aam-Digital/aam-services#7
